### ISSUE TITLE
Suggestions to the sponsorship page

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-conference#133]
1. Can we add a big button at the bottom, call to action: Sponsor us
Example mockup (just suggestion, I'm not good with CSS)
![Screenshot 2024-08-20 at 11 24 51 AM](https://github.com/user-attachments/assets/08db6cfb-1ddc-4719-acd6-6610603cf35b)

2. Can we show the sponsorship email address more explicitly? Currently it is hidden inside "Get in touch" link.
Perhaps, instead of saying "please get in touch," it can say "please get in touch by writing to sponsors@pyladies.com"
![Screenshot 2024-08-20 at 11 29 22 AM](https://github.com/user-attachments/assets/5c5cdfce-d9d1-4860-993f-fcbae9dd18e9)

**Comment by cmaureir** [comment]
(I'm sorry I pushed directly instead of opening a new PR :'( but this is solved)

**Comment by Mariatta** [comment]
Thank you!
