### ISSUE TITLE
Communications

### ISSUE THREAD

**Issue by elkabuitrago** [pyladies/global-conference#15]
- Event announcement in social media
- CFP announcement 
- Atendees
- Speakers
- Sponsors

**Comment by DennyPerez18** [comment]
All content of social media posts created here:
https://www.notion.so/galileos-paradox/PyLadiesCon-Social-Media-Planning-c4a865d8cb714e618a4e220d3ed4c39d?pvs=4

All blog post content created here:
https://drive.google.com/drive/folders/1AV0MIFECapFwnsvCOmQvSNjdYh8FKQ6-?usp=drive_link
