### ISSUE TITLE
Sponsors proposal

### ISSUE THREAD

**Issue by elkabuitrago** [pyladies/global-conference#19]

**Comment by DennyPerez18** [comment]
Proposals to the PSF Done:

https://drive.google.com/file/d/1Y5xXduXDeOV2wHRBykjcAy-xHZ0EK_PR/view?usp=drive_link

https://drive.google.com/file/d/1IHuvLhPk19hQu3YI06QHC2mKUuZ2nQif/view?usp=drive_link
