### ISSUE TITLE
Sponsors searching

### ISSUE THREAD

**Issue by elkabuitrago** [pyladies/global-conference#20]

**Comment by DennyPerez18** [comment]
The link to suggestions or recommendations for potential sponsors spreadsheet is:
https://docs.google.com/spreadsheets/d/11yCGo-F5nVWXjM4LDTLjjmBPN3RCIJXIepKQb-z2bU4/edit?usp=drivesdk

Please either enter possibilities directly into the sheet or post them here and tag @nceder
