### ISSUE TITLE
Videos preparation

### ISSUE THREAD

**Issue by elkabuitrago** [pyladies/global-conference#26]
Opening, breaks, sponsors videos preparation

**Comment by cmaureir** [comment]
If we  want to reach to other communities, we should do this soon, so people have time to send either a short 5 seconds clip of their community or a slide with information.

**Comment by DennyPerez18** [comment]
In Progress:
https://drive.google.com/drive/folders/1Lo_3pii0RxLcMm6iXgfiRqnv-uFP5A1w?usp=drive_link
