### ISSUE TITLE
Create the Speaker's page 

### ISSUE THREAD

**Issue by georgically** [pyladies/global-conference#57]
To create the speakers page based on the design created:
[Desktop](https://www.figma.com/file/ow9vzSa50YsUDaI65RJB81/PyLadies-Conference?type=design&node-id=93-924&mode=design&t=WK0eMN0gnCmrKozn-4)

[Tablet](https://www.figma.com/file/ow9vzSa50YsUDaI65RJB81/PyLadies-Conference?type=design&node-id=123-5551&mode=design&t=WK0eMN0gnCmrKozn-4)

[Mobile](https://www.figma.com/file/ow9vzSa50YsUDaI65RJB81/PyLadies-Conference?type=design&node-id=141-5305&mode=design&t=WK0eMN0gnCmrKozn-4)

add new template on 
https://github.com/pyladies/global-conference/tree/52e812b728b14af1b8dbc51e07244f222f0acc57/generate_site/templates
as "speakers-base"

**Comment by cmaureir** [comment]
Deployed already
