### ISSUE TITLE
Create individual talk page 

### ISSUE THREAD

**Issue by georgically** [pyladies/global-conference#58]
To create the individual talk page based on the design created:
[Desktop](https://www.figma.com/file/ow9vzSa50YsUDaI65RJB81/PyLadies-Conference?type=design&node-id=175-18342&mode=design&t=WK0eMN0gnCmrKozn-4)

[Tablet](https://www.figma.com/file/ow9vzSa50YsUDaI65RJB81/PyLadies-Conference?type=design&node-id=175-17791&mode=design&t=WK0eMN0gnCmrKozn-4)

[Mobile](https://www.figma.com/file/ow9vzSa50YsUDaI65RJB81/PyLadies-Conference?type=design&node-id=174-12999&mode=design&t=WK0eMN0gnCmrKozn-4)

add new template on
https://github.com/pyladies/global-conference/tree/52e812b728b14af1b8dbc51e07244f222f0acc57/generate_site/templates
as "talk-base"

**Comment by cmaureir** [comment]
In the meantime, I added the talks under each speaker on the speaker page, with a link to the pretalx-talk information, instead of our own format. I'd keep this open until we add our own style.
