### ISSUE TITLE
Add auth0 by Okta logo as Booster sponsor

### ISSUE THREAD

**Issue by nceder** [pyladies/global-conference#77]
Add Auth0 as booster sponsor  ($1000), so bigger than Partner if possible.

Logo: https://drive.google.com/file/d/1NuzaUk1G2RAtlAI23gssxHD9W72rx4iQ/view?usp=drive_link
Link: https://a0.to/pyladiescon

Social media copy: https://docs.google.com/document/d/143yEpA4TL99Uv_vY70sdFwNlxgxb4DcQoArxA0wkKy0/edit?usp=drive_link

**Comment by cmaureir** [comment]
Not sure what do do with the Social media copy. Should that be included on the web @nceder  ?
