### ISSUE TITLE
Schedule UX a bit confusing

### ISSUE THREAD

**Issue by willingc** [pyladies/global-conference#93]
Schedule use of filter and time entry is a bit confusing. If someone has time to check the UI that would be great.

---

Update: It looks like the button (Filter) and dropdown (Timezone) is in the pretalx app which will make this a pain to change.

If there are more questions about the schedule, perhaps adding a little text under the "Schedule" heading.
Perhaps: `Use the Filter button to select the desired track. The dropdown next to the button will allow changing timezone from UTC to local timezone.`

---

Thanks for all of the work on the site 💐 ✨

**Comment by cmaureir** [comment]
Thanks for the suggestion!, I think having a little banner with the info is a cool idea.
![Screenshot 2023-11-29 at 19-09-43 PyLadiesCon 2023 - Schedule](https://github.com/pyladies/global-conference/assets/177982/f3652f10-fcf8-42fa-8d56-4278dfdf0d6d)
